### ISSUE TITLE
Problem when setting colors

### ISSUE THREAD

**Issue by cdric0701** [YanNerio/emotion-ratings#4]
Hello,
Thanks for this great plugin, very complete !
However I experience a little problem when setting colors on the emojis.
For example:
`color: "green",`

My emojis still stay the same ... the color doesn't change.
I have this problem on Chrome.
Do you know how can I resolve this ?

Thanks in advance.

**Comment by YanNerio** [comment]
Hello @cdric0701  thanks for your feedback!
In order to set a color you should use the CSS code, but this feature will only work depending on the OS you are using since in mobile or Mac the emojis does not appear as unicode characters but as the image itself.
for example using Mac Os I see them like this (yancinerio.com/emotion-ratings)
<img width="1205" alt="screen shot 2018-12-04 at 1 49 09 pm" src="https://user-images.githubusercontent.com/7425700/49468752-69c8f700-f7cb-11e8-8264-9a837f1171b0.png">

**Comment by cdric0701** [comment]
Okay thanks ! 👍

**Comment by cdric0701** [comment]
And there i no possibility to force it to be an emoji or to be in a color on a all plateform ? (explorer, firefox, MacOS, Windows etc) ? Thanks

**Comment by YanNerio** [comment]
Yes, there is one:
If you include the font called **Symbola**  and add this font-family to your emojis container, you will be able to see the unicode figures and not the emojis, so you will be able to add the color you want!

[Symbola font](http://users.teilar.gr/~g1951d/Symbola.zip)
